### PR TITLE
Improved drupal formula

### PR DESCRIPTION
**Pull request by aboe76**
Improved drupal module to install only drupal
    
Removed apache/nginx/lighthttpd part, this should be done in a different
state like apache-formula,nginx-formula
    
Added map.jinja logic to make the formula more in line with saltstack best practices
    
Improved the drupal logic so it only updates the file permissions if the drupal
file is downloaded again, todo is improve the logic of file permissions
see: https://www.drupal.org/node/244924

### CODE REVIEW

**Comment by babilen** [comment]
I agree with your reasoning, but this needs some more detailed review, bu someone more familiar with Drupal.

**Comment by whiteinge** [comment]
Great changes overall. Agree about dep'ing on other webserver Formulas.

@fintanmm you've done a bunch of work here, do you have a few cycles to take a look?

**Comment by aboe76** [comment]
I have worked some more on the logic and mapping with the help of two debian minions...
I think I have fixed most of the logic. Only thing left is to improve the file permissions part some more.

**Comment by aboe76** [comment]
Updated the pull request with some more improvements, I think it's ready to be used.

**Comment by whiteinge** [comment]
@aboe76 good stuff. Thanks for staying with it this whole time.

**Pull request merged**
